//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 08:57:05 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://slava/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package slava.courses;
